INSERT INTO products (
  name,
  slug,
  description,
  category,
  gold_weight_grams,
  gold_purity,
  making_charge_type,
  making_charge_value,
  jeweller_margin,
  images,
  stock_quantity,
  is_active,
  is_featured,
  hallmark_number
) VALUES
(
  'Classic Solitaire Ring',
  'classic-solitaire-ring',
  'A timeless 22K gold solitaire ring with a polished finish. Crafted by hand in our Jaipur atelier, this piece pairs effortlessly with both traditional and contemporary wear.',
  'ring',
  4.200,
  '22K',
  'percentage',
  12.00,
  800.00,
  ARRAY['/placeholders/ring.svg'],
  8,
  TRUE,
  TRUE,
  'BIS-HM-2024-001'
),
(
  'Kundan Jhumka Earrings',
  'kundan-jhumka-earrings',
  'Traditional Kundan-set jhumka earrings in 22K gold. Each piece is hand-set with uncut stones and finished with a meenakari back. A staple for festive occasions.',
  'earring',
  6.800,
  '22K',
  'percentage',
  15.00,
  1200.00,
  ARRAY['/placeholders/earring.svg'],
  5,
  TRUE,
  TRUE,
  'BIS-HM-2024-002'
),
(
  'Rope Chain Necklace',
  'rope-chain-necklace',
  'A 22K gold rope chain with a secure lobster clasp. 18 inches in length, 2mm width. Versatile enough to wear alone or layered with a pendant.',
  'chain',
  8.500,
  '22K',
  'fixed',
  1200.00,
  600.00,
  ARRAY['/placeholders/chain.svg'],
  12,
  TRUE,
  FALSE,
  'BIS-HM-2024-003'
),
(
  'Temple Bangle Set',
  'temple-bangle-set',
  'A pair of 22K gold temple bangles with intricate deity motifs. Hand-engraved by third-generation artisans from Thrissur. Sold as a pair.',
  'bangle',
  18.000,
  '22K',
  'percentage',
  10.00,
  2500.00,
  ARRAY['/placeholders/bangle.svg'],
  3,
  TRUE,
  TRUE,
  'BIS-HM-2024-004'
),
(
  'Floral Pendant',
  'floral-pendant',
  'A delicate 22K gold floral pendant with a matte finish centre and polished petals. Includes an 18-inch box chain. Perfect for everyday luxury.',
  'pendant',
  3.100,
  '22K',
  'fixed',
  650.00,
  500.00,
  ARRAY['/placeholders/pendant.svg'],
  10,
  TRUE,
  FALSE,
  'BIS-HM-2024-005'
),
(
  'Layered Choker Necklace',
  'layered-choker-necklace',
  'A three-strand 22K gold choker with a traditional South Indian design. Features a central Lakshmi coin motif. Adjustable length from 14 to 16 inches.',
  'necklace',
  22.500,
  '22K',
  'percentage',
  12.00,
  3000.00,
  ARRAY['/placeholders/necklace.svg'],
  2,
  TRUE,
  TRUE,
  'BIS-HM-2024-006'
),
(
  'Twisted Band Ring',
  'twisted-band-ring',
  'A contemporary 22K gold twisted band ring. Minimalist design with a high-polish finish. Available in standard sizes and easy to style for everyday wear.',
  'ring',
  3.500,
  '22K',
  'percentage',
  10.00,
  600.00,
  ARRAY['/placeholders/ring.svg'],
  15,
  TRUE,
  FALSE,
  'BIS-HM-2024-007'
),
(
  'Antique Haaram Necklace',
  'antique-haaram-necklace',
  'A long 22K gold haaram necklace with antique finish and ruby-red enamel accents. 30 inches in length. A statement piece for weddings and ceremonies.',
  'necklace',
  35.000,
  '22K',
  'percentage',
  14.00,
  5000.00,
  ARRAY['/placeholders/necklace.svg'],
  1,
  TRUE,
  FALSE,
  'BIS-HM-2024-008'
),
(
  'Lotus Stud Earrings',
  'lotus-stud-earrings',
  'Petite 22K gold lotus stud earrings with a push-back closure. Lightweight and comfortable for daily wear. Each stud is 8mm in diameter.',
  'earring',
  2.200,
  '22K',
  'fixed',
  400.00,
  350.00,
  ARRAY['/placeholders/earring.svg'],
  20,
  TRUE,
  FALSE,
  'BIS-HM-2024-009'
),
(
  'Broad Kangan Bangle',
  'broad-kangan-bangle',
  'A single broad 22K gold kangan bangle with a hammered texture and smooth inner surface. 10mm width. Sold individually; order two for a pair.',
  'bangle',
  12.000,
  '22K',
  'percentage',
  11.00,
  1800.00,
  ARRAY['/placeholders/bangle.svg'],
  6,
  TRUE,
  FALSE,
  'BIS-HM-2024-010'
);
